### ISSUE TITLE
ARE YOU OKAY?

### ISSUE THREAD

**Issue by soullivaneuh** [feross/are-feross-and-mafintosh-stuck-in-an-elevator.tk#1]
ARE YOU OKAY?

'CAUSE BEING STUCK IN AN ELEVATOR IS REALLY REALLY A BAD THING.

REGARDS!

**Comment by feross** [comment]
Thanks, we're okay because v2.0.0 was released!

https://www.npmjs.com/package/are-feross-and-mafintosh-stuck-in-an-elevator

**Comment by soullivaneuh** [comment]
\o/
